name: crownstone-hub
version: "0.11.0"
summary: Crownstone gateway.
description: |
  Provides a REST API for your Crownstones: https://crownstone.rocks
  This snap is made to run on the Crownstone Hub, which enables:

    * Energy monitoring.
    * Integration with other smart home devices.
    * Control via the internet.

  Requires a Crownstone USB dongle to connect to your Crownstones via the mesh.

#base: core20
base: core18
grade: stable
confinement: strict

#plugs:
#    home:
#    network:
#    network-bind:

parts:
  crownstone-hub:
    # See 'snapcraft plugins'
#    plugin: npm
#    npm-node-version: "12.18.3"

    plugin: nodejs
    nodejs-version: "12.18.3"
    nodejs-package-manager: yarn
    nodejs-yarn-version: "v1.22.4"
    source: .
    source-type: local

#    build:
#      - openssl-hub.conf
    
#    prime:
#      - openssl-hub.conf

#    build-packages:
#    stage-packages:

  content:
    source: config
    source-type: local
    plugin: dump

  bin:
    source: bin
    source-type: local
    plugin: dump

apps:
  crownstone-hub:
    command: run.sh
    daemon: simple
    restart-condition: always
    restart-delay: 2s
    environment:
      LANG: C.UTF-8
      CS_HUB_HTTPS_CERTIFICATE_PATH: $SNAP_COMMON
      CS_HUB_SLL_CONFIG_PATH: $SNAP
      CS_HUB_CONFIG_PATH: $SNAP_COMMON/config
      CS_FILE_LOGGING_DIRNAME: $SNAP_COMMON/logs
#      CS_FILE_LOGGING_BASENAME: 
      CS_ENABLE_FILE_LOGGING: "true"
      CS_FILE_LOGGING_LEVEL: "info"
      CS_CONSOLE_LOGGING_LEVEL: "none"
#      CS_HUB_UART_PORT: "/dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_014A641C-if00-port0"
      CS_UART_SEARCH_BY_ID: "true"
      CS_UART_SEARCH_BY_ID_PATH: "/dev/serial/by-id"
      CS_UART_SEARCH_BY_ID_PATTERN: "usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_.*"
    plugs:
      - bluetooth-control
      - bluez
      - network
      - network-bind
      - removable-media
      - serial-port
